exports.ERR_MSG = {
    INTERNAL_ERROR: "INTERNAL_ERROR",
    EXTERNAL_ERROR: "EXTERNAL_ERROR",

    INVALID_PARAMETER: "INVALID_PARAMETER",

    NOW_CHECKING: "NOW_CHECKING",

    UNAUTHORIZED: "UNAUTHORIZED",
    BLOCKED_AGENT: "BLOCKED_AGENT",
    INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
    INVALID_PERMISSION: "INVALID_PERMISSION",
    CANNOT_UPDATE_AGENT: "CANNOT_UPDATE_AGENT",

    INVALID_AGENT: "INVALID_AGENT",
    INVALID_PARENT_AGENT: "INVALID_PARENT_AGENT",
    INVALID_PARENT_AGENT_TYPE: "INVALID_PARENT_AGENT_TYPE",

    INSUFFICIENT_PARENT_FUNDS: "INSUFFICIENT_PARENT_FUNDS",
    INSUFFICIENT_AGENT_FUNDS: "INSUFFICIENT_AGENT_FUNDS",
    INSUFFICIENT_USER_FUNDS: "INSUFFICIENT_USER_FUNDS",

    INVALID_USER: "INVALID_USER",

    INVALID_CHECKUP: "INVALID_CHECKUP",
    INVALID_MESSAGE: "INVALID_MESSAGE",
    INVALID_POPUP: "INVALID_POPUP",

    DUPLICATED_AGENT: "DUPLICATED_AGENT",

    INVALID_PROVIDER: "INVALID_PROVIDER",
    INVALID_PLAYER: "INVALID_PLAYER",
    INVALID_CALL: "INVALID_CALL",
    NOT_FOUND_CALL: "NOT_FOUND_CALL",
    PLAYER_BET_CHANGED: "PLAYER_BET_CHANGED",

    EXIST_CALL: "EXIST_PROCESSING_CALL",
};
